runtime: python
env: flex
entrypoint: gunicorn -k gevent -b :$PORT main:app

runtime_config:
  python_version: 2

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "service-account.json"

resources:
  cpu: 1
  memory_gb: 3
  disk_size_gb: 10